// Interview-prep problem bank — offline, no deps.
// Each problem has BOTH a quick "drill" (short-wait recall) and a full statement
// (long-run solving), so the watcher can adapt to how long Claude is working.
//
// Fields:
//   id         stable key (used by spaced-repetition stats)
//   title      problem name
//   diff       Easy | Medium | Hard
//   pattern    the technique tag (this is what you're really drilling)
//   drillQ     one-line recall prompt for short waits
//   drillA     the answer to the drill (the key idea / template)
//   prompt     full problem statement
//   examples   example I/O
//   hints      progressive hints (revealed one at a time)
//   approach   solution sketch
//   complexity time/space

module.exports = [
  // ───────────────────────── Arrays & Hashing ─────────────────────────
  {
    id: "two-sum", title: "Two Sum", diff: "Easy", pattern: "Hash Map",
    drillQ: "Return indices of two nums that sum to target, in O(n)?",
    drillA: "One pass + hashmap value→index. For each x, check if (target−x) was seen.",
    prompt: "Given an array nums and an int target, return indices of the two numbers that add up to target. Exactly one solution; no reuse.",
    examples: "nums=[2,7,11,15], target=9 → [0,1]",
    hints: ["Brute force is O(n²). Can you trade space for time?", "What have you already seen as you scan left→right?", "Store value→index in a map; look up target−x."],
    approach: "Single pass; for each x compute need=target−x; if need in map return [map[need], i]; else map[x]=i.",
    complexity: "Time O(n), Space O(n)",
  },
  {
    id: "contains-duplicate", title: "Contains Duplicate", diff: "Easy", pattern: "Hash Set",
    drillQ: "Does an array contain any duplicate value?",
    drillA: "Add to a set while scanning; if already present → true. (Or len(set)!=len(arr).)",
    prompt: "Return true if any value appears at least twice in the array, false if every element is distinct.",
    examples: "[1,2,3,1] → true ; [1,2,3,4] → false",
    hints: ["O(n²) compares each pair — too slow.", "A set gives O(1) membership."],
    approach: "Scan; maintain a set; return true on first repeat.",
    complexity: "Time O(n), Space O(n)",
  },
  {
    id: "group-anagrams", title: "Group Anagrams", diff: "Medium", pattern: "Hash Map",
    drillQ: "Group words that are anagrams of each other — what's the map key?",
    drillA: "Key = sorted chars, OR a 26-length count tuple. Bucket words under that key.",
    prompt: "Given an array of strings, group the anagrams together. Return the groups in any order.",
    examples: "['eat','tea','tan','ate','nat','bat'] → [['eat','tea','ate'],['tan','nat'],['bat']]",
    hints: ["Anagrams share the same multiset of letters.", "Canonicalize each word to a key.", "Count tuple (len 26) avoids the O(k log k) sort."],
    approach: "For each word build a key (sorted string or 26-count tuple); append word to dict[key]; return dict.values().",
    complexity: "Time O(n·k), Space O(n·k)  (k = word length)",
  },
  {
    id: "top-k-frequent", title: "Top K Frequent Elements", diff: "Medium", pattern: "Bucket Sort / Heap",
    drillQ: "Return the k most frequent elements faster than sorting?",
    drillA: "Count freqs, then bucket sort by frequency (index=count). O(n). Or a size-k heap (O(n log k)).",
    prompt: "Given nums and an int k, return the k most frequent elements.",
    examples: "nums=[1,1,1,2,2,3], k=2 → [1,2]",
    hints: ["Counting is the easy part.", "Frequencies are bounded by n — use them as bucket indices."],
    approach: "Count with a map; buckets[freq] = list of values; walk buckets high→low collecting k.",
    complexity: "Time O(n), Space O(n)",
  },
  {
    id: "product-except-self", title: "Product of Array Except Self", diff: "Medium", pattern: "Prefix/Suffix",
    drillQ: "out[i]=product of all but nums[i], no division, O(n)?",
    drillA: "Prefix products L→R into out, then multiply by running suffix product R→L.",
    prompt: "Return an array where out[i] is the product of every element except nums[i]. No division; O(n).",
    examples: "[1,2,3,4] → [24,12,8,6]",
    hints: ["out[i] = (product left of i) × (product right of i).", "Two passes; keep running products."],
    approach: "Pass 1: out[i]=prefix product. Pass 2 from right: out[i]*=suffix, suffix*=nums[i].",
    complexity: "Time O(n), Space O(1) extra (output aside)",
  },

  // ───────────────────────── Two Pointers ─────────────────────────
  {
    id: "valid-palindrome", title: "Valid Palindrome", diff: "Easy", pattern: "Two Pointers",
    drillQ: "Is a string a palindrome ignoring non-alnum & case?",
    drillA: "Two pointers from both ends; skip non-alnum; compare lowercased chars.",
    prompt: "Return true if the string is a palindrome considering only alphanumeric characters and ignoring case.",
    examples: "'A man, a plan, a canal: Panama' → true",
    hints: ["You don't need to build a cleaned copy.", "Move l→ and ←r, skipping junk."],
    approach: "l=0,r=n−1; while l<r skip non-alnum; if lower(s[l])!=lower(s[r]) return false; l++,r−−.",
    complexity: "Time O(n), Space O(1)",
  },
  {
    id: "3sum", title: "3Sum", diff: "Medium", pattern: "Two Pointers",
    drillQ: "All unique triplets summing to 0?",
    drillA: "Sort; fix i; two-pointer (l,r) on the rest; skip dups on i, l, r.",
    prompt: "Return all unique triplets [a,b,c] in nums with a+b+c=0. No duplicate triplets.",
    examples: "[-1,0,1,2,-1,-4] → [[-1,-1,2],[-1,0,1]]",
    hints: ["Sorting unlocks the two-pointer move.", "Skip duplicates at each level to avoid repeats."],
    approach: "Sort. For each i (skip dup), set l=i+1,r=n−1; move based on sum vs 0; record on hit and skip dups.",
    complexity: "Time O(n²), Space O(1) (excl. output)",
  },
  {
    id: "container-most-water", title: "Container With Most Water", diff: "Medium", pattern: "Two Pointers",
    drillQ: "Max water area between two lines, O(n)?",
    drillA: "Pointers at both ends; area=min(h)*width; move the SHORTER wall inward.",
    prompt: "Given heights, pick two lines that with the x-axis form a container holding the most water. Return max area.",
    examples: "[1,8,6,2,5,4,8,3,7] → 49",
    hints: ["Width shrinks as pointers converge.", "Moving the taller wall can't help — move the shorter."],
    approach: "l,r at ends; area=min(h[l],h[r])*(r−l); keep max; move pointer at smaller height.",
    complexity: "Time O(n), Space O(1)",
  },

  // ───────────────────────── Sliding Window ─────────────────────────
  {
    id: "best-time-stock", title: "Best Time to Buy & Sell Stock", diff: "Easy", pattern: "Sliding Window / Greedy",
    drillQ: "Max profit from one buy then one later sell?",
    drillA: "Track min price so far; profit=max(profit, price−min) as you scan.",
    prompt: "Given daily prices, maximize profit from buying one day and selling a later day. Return 0 if impossible.",
    examples: "[7,1,5,3,6,4] → 5  (buy 1, sell 6)",
    hints: ["You only need the cheapest price seen before today.", "One pass, two variables."],
    approach: "minP=∞; for p: best=max(best,p−minP); minP=min(minP,p).",
    complexity: "Time O(n), Space O(1)",
  },
  {
    id: "longest-substr-no-repeat", title: "Longest Substring Without Repeating Chars", diff: "Medium", pattern: "Sliding Window",
    drillQ: "Length of longest substring with all-distinct chars?",
    drillA: "Window with a set/last-index map; on repeat move left past the duplicate; track max width.",
    prompt: "Return the length of the longest substring without repeating characters.",
    examples: "'abcabcbb' → 3 ('abc')",
    hints: ["Grow right; when a char repeats, shrink from left.", "A last-seen-index map lets left jump."],
    approach: "Map char→lastIndex; for r: if s[r] seen ≥ l, l=last+1; update last; best=max(best,r−l+1).",
    complexity: "Time O(n), Space O(min(n,charset))",
  },
  {
    id: "longest-repeat-replace", title: "Longest Repeating Character Replacement", diff: "Medium", pattern: "Sliding Window",
    drillQ: "Longest run of one letter if you may change ≤k chars?",
    drillA: "Window valid when (windowLen − maxFreqInWindow) ≤ k; grow right, shrink left when invalid.",
    prompt: "Given a string and int k, you may replace up to k characters. Return the length of the longest substring of a single repeated letter achievable.",
    examples: "s='AABABBA', k=1 → 4",
    hints: ["Cost to make window uniform = len − count of its most frequent char.", "Keep window valid; track best."],
    approach: "Counts in window; maxFreq=max seen; while (winLen−maxFreq)>k shrink left; best=max(best,winLen).",
    complexity: "Time O(n), Space O(1) (26 letters)",
  },
  {
    id: "min-window-substring", title: "Minimum Window Substring", diff: "Hard", pattern: "Sliding Window",
    drillQ: "Smallest substring of s containing all chars of t (with multiplicity)?",
    drillA: "Need-count map + 'have/need' matched counter; expand right to satisfy, contract left to minimize.",
    prompt: "Return the minimum window substring of s that contains every character of t (including duplicates). '' if none.",
    examples: "s='ADOBECODEBANC', t='ABC' → 'BANC'",
    hints: ["Track how many required chars are currently satisfied.", "When all satisfied, shrink from the left to find the min."],
    approach: "need=count(t); have=0; expand r updating window counts; when have==len(need) keys, shrink l recording best; pop affects have.",
    complexity: "Time O(n), Space O(charset)",
  },

  // ───────────────────────── Stack ─────────────────────────
  {
    id: "valid-parens", title: "Valid Parentheses", diff: "Easy", pattern: "Stack",
    drillQ: "Is a string of ()[]{} validly nested?",
    drillA: "Push opens; on a close, top must be its match — else invalid; stack empty at end.",
    prompt: "Given a string of '()[]{}', determine if brackets are validly opened and closed.",
    examples: "'([{}])' → true ; '(]' → false",
    hints: ["LIFO matching is a stack.", "Map close→open."],
    approach: "For c: if open push; else stack must be non-empty and top matches, pop; valid iff stack empty.",
    complexity: "Time O(n), Space O(n)",
  },
  {
    id: "daily-temperatures", title: "Daily Temperatures", diff: "Medium", pattern: "Monotonic Stack",
    drillQ: "Days until a warmer temperature, for each day?",
    drillA: "Decreasing stack of indices; pop while current temp > stacked temp, setting answer = i−poppedIdx.",
    prompt: "Given daily temps, return for each day how many days until a warmer day (0 if none).",
    examples: "[73,74,75,71,69,72,76,73] → [1,1,4,2,1,1,0,0]",
    hints: ["You want the next greater element to the right.", "Keep indices of unresolved (decreasing) days on a stack."],
    approach: "Stack of indices; for i: while stack and t[i]>t[top]: j=pop, ans[j]=i−j; push i.",
    complexity: "Time O(n), Space O(n)",
  },
  {
    id: "largest-rect-histogram", title: "Largest Rectangle in Histogram", diff: "Hard", pattern: "Monotonic Stack",
    drillQ: "Biggest rectangle area under a histogram?",
    drillA: "Increasing stack of (index,height); when a shorter bar comes, pop and compute area=h*(i−prevIndex).",
    prompt: "Given bar heights of width 1, return the area of the largest rectangle in the histogram.",
    examples: "[2,1,5,6,2,3] → 10",
    hints: ["For each bar, how far left/right can it extend at its own height?", "A monotonic increasing stack finds both boundaries."],
    approach: "Stack of (start,height); on h[i]<top.height, pop computing area=height*(i−start), carry start; push (start,h[i]). Flush at end.",
    complexity: "Time O(n), Space O(n)",
  },

  // ───────────────────────── Binary Search ─────────────────────────
  {
    id: "binary-search", title: "Binary Search", diff: "Easy", pattern: "Binary Search",
    drillQ: "Find target in a sorted array in O(log n) — loop invariant?",
    drillA: "lo=0,hi=n−1; while lo<=hi: mid=(lo+hi)>>1; shrink toward target. Avoid overflow with lo+(hi−lo)/2.",
    prompt: "Given a sorted array and a target, return its index or −1.",
    examples: "[-1,0,3,5,9,12], 9 → 4",
    hints: ["Halve the search space each step.", "Mind the <= and mid±1 to guarantee progress."],
    approach: "while lo<=hi: mid; if a[mid]==t return mid; if a[mid]<t lo=mid+1 else hi=mid−1; return −1.",
    complexity: "Time O(log n), Space O(1)",
  },
  {
    id: "search-rotated", title: "Search in Rotated Sorted Array", diff: "Medium", pattern: "Binary Search",
    drillQ: "Find target in a rotated sorted array, O(log n)?",
    drillA: "Binary search; one half is always sorted — test if target lies in that sorted half, else go other way.",
    prompt: "A sorted array rotated at an unknown pivot (distinct values). Return target's index or −1.",
    examples: "[4,5,6,7,0,1,2], 0 → 4",
    hints: ["At any mid, the left or right half is fully sorted.", "Decide which half is sorted, then whether target is inside it."],
    approach: "If a[lo]<=a[mid]: left sorted → if a[lo]<=t<a[mid] go left else right. Else right sorted → symmetric.",
    complexity: "Time O(log n), Space O(1)",
  },
  {
    id: "find-min-rotated", title: "Find Minimum in Rotated Sorted Array", diff: "Medium", pattern: "Binary Search",
    drillQ: "Min of a rotated sorted array, O(log n)?",
    drillA: "Compare a[mid] to a[hi]: if a[mid]>a[hi] min is right (lo=mid+1) else hi=mid. Answer at lo.",
    prompt: "Find the minimum element of a rotated sorted array of distinct values.",
    examples: "[4,5,6,7,0,1,2] → 0",
    hints: ["The pivot is the only place where order breaks.", "Compare mid to the rightmost element."],
    approach: "while lo<hi: mid; if a[mid]>a[hi] lo=mid+1 else hi=mid; return a[lo].",
    complexity: "Time O(log n), Space O(1)",
  },
  {
    id: "koko-bananas", title: "Koko Eating Bananas", diff: "Medium", pattern: "Binary Search on Answer",
    drillQ: "Min eating speed to finish piles within h hours?",
    drillA: "Binary search speed k in [1,max]; feasible(k)=Σ ceil(pile/k) ≤ h. Find smallest feasible k.",
    prompt: "Piles of bananas; in h hours Koko picks a speed k and eats k/hour per pile (per hour, one pile). Return the minimum integer k to finish all within h hours.",
    examples: "piles=[3,6,7,11], h=8 → 4",
    hints: ["Answer is monotonic: bigger k is never worse.", "Search the answer space, not the array."],
    approach: "lo=1,hi=max(piles); while lo<hi: mid; if hoursNeeded(mid)<=h hi=mid else lo=mid+1; return lo.",
    complexity: "Time O(n log maxPile), Space O(1)",
  },

  // ───────────────────────── Linked List ─────────────────────────
  {
    id: "reverse-linked-list", title: "Reverse Linked List", diff: "Easy", pattern: "Linked List",
    drillQ: "Reverse a singly linked list in O(1) space?",
    drillA: "prev=null; while cur: nxt=cur.next; cur.next=prev; prev=cur; cur=nxt. Return prev.",
    prompt: "Reverse a singly linked list and return the new head.",
    examples: "1→2→3→4→5 → 5→4→3→2→1",
    hints: ["You only need three pointers.", "Save next before you rewire."],
    approach: "Iterative pointer flip (prev/cur/next), or recurse and fix head.next.next=head.",
    complexity: "Time O(n), Space O(1)",
  },
  {
    id: "merge-two-lists", title: "Merge Two Sorted Lists", diff: "Easy", pattern: "Linked List",
    drillQ: "Merge two sorted linked lists into one sorted list?",
    drillA: "Dummy head + tail; splice the smaller head each step; attach remaining tail at end.",
    prompt: "Merge two sorted linked lists into one sorted list and return its head.",
    examples: "1→2→4 , 1→3→4 → 1→1→2→3→4→4",
    hints: ["A dummy node removes head-edge cases.", "Compare heads, advance the chosen list."],
    approach: "dummy; tail; while both: pick smaller, tail.next=it, advance; tail.next=remaining.",
    complexity: "Time O(n+m), Space O(1)",
  },
  {
    id: "linked-list-cycle", title: "Linked List Cycle", diff: "Easy", pattern: "Fast & Slow Pointers",
    drillQ: "Detect a cycle in a linked list, O(1) space?",
    drillA: "Floyd's: slow +1, fast +2; if they ever meet → cycle; if fast hits null → no cycle.",
    prompt: "Return true if the linked list has a cycle.",
    examples: "3→2→0→-4→(back to 2) → true",
    hints: ["A set of seen nodes works but uses O(n).", "Two speeds must collide inside a loop."],
    approach: "slow=fast=head; while fast and fast.next: slow=slow.next, fast=fast.next.next; if equal return true.",
    complexity: "Time O(n), Space O(1)",
  },
  {
    id: "remove-nth-end", title: "Remove Nth Node From End", diff: "Medium", pattern: "Fast & Slow Pointers",
    drillQ: "Remove the nth node from the end in one pass?",
    drillA: "Advance fast n steps; then move fast & slow together until fast.next null; slow.next=slow.next.next. Use dummy.",
    prompt: "Remove the nth node from the end of the list and return the head.",
    examples: "1→2→3→4→5, n=2 → 1→2→3→5",
    hints: ["Gap of n between two pointers locates the target.", "A dummy head handles removing the first node."],
    approach: "dummy→head; fast advances n; then fast&slow advance until fast.next is null; slow.next=slow.next.next.",
    complexity: "Time O(n), Space O(1)",
  },

  // ───────────────────────── Trees ─────────────────────────
  {
    id: "invert-tree", title: "Invert Binary Tree", diff: "Easy", pattern: "Tree DFS",
    drillQ: "Invert (mirror) a binary tree?",
    drillA: "Recurse: swap left/right children, then invert each subtree (or BFS/DFS with a swap).",
    prompt: "Invert a binary tree (mirror it) and return the root.",
    examples: "[4,2,7,1,3,6,9] → [4,7,2,9,6,3,1]",
    hints: ["Swap children at every node.", "Recursion or a queue both work."],
    approach: "if node: swap node.left,node.right; recurse both.",
    complexity: "Time O(n), Space O(h)",
  },
  {
    id: "max-depth-tree", title: "Maximum Depth of Binary Tree", diff: "Easy", pattern: "Tree DFS",
    drillQ: "Max depth of a binary tree?",
    drillA: "1 + max(depth(left), depth(right)); null → 0.",
    prompt: "Return the maximum depth (root→deepest leaf node count) of a binary tree.",
    examples: "[3,9,20,null,null,15,7] → 3",
    hints: ["Depth of a node = 1 + max child depth.", "Base case is the null child."],
    approach: "return node? 1+max(dfs(l),dfs(r)) : 0.",
    complexity: "Time O(n), Space O(h)",
  },
  {
    id: "validate-bst", title: "Validate Binary Search Tree", diff: "Medium", pattern: "Tree DFS",
    drillQ: "Is a tree a valid BST?",
    drillA: "DFS carrying (low, high) bounds; each node must be strictly within; tighten bounds going down. (Or check in-order is strictly increasing.)",
    prompt: "Determine whether a binary tree is a valid binary search tree (left<node<right for the whole subtree).",
    examples: "[5,1,4,null,null,3,6] → false",
    hints: ["Local left<node<right is NOT enough — bounds propagate.", "Pass allowed (min,max) range down."],
    approach: "dfs(node,lo,hi): if null true; if !(lo<val<hi) false; recurse left (lo,val) & right (val,hi).",
    complexity: "Time O(n), Space O(h)",
  },
  {
    id: "lca-bst", title: "Lowest Common Ancestor of a BST", diff: "Medium", pattern: "BST",
    drillQ: "LCA of two nodes in a BST?",
    drillA: "Walk from root: both < node → go left; both > node → go right; else (split) this node is the LCA.",
    prompt: "Given a BST and two nodes p,q, return their lowest common ancestor.",
    examples: "root=[6,2,8,...], p=2,q=8 → 6",
    hints: ["The BST ordering tells you which way both targets lie.", "The split point is the LCA."],
    approach: "node=root; while: if p,q<node go left; elif p,q>node go right; else return node.",
    complexity: "Time O(h), Space O(1)",
  },
  {
    id: "level-order", title: "Binary Tree Level Order Traversal", diff: "Medium", pattern: "Tree BFS",
    drillQ: "Return nodes level by level?",
    drillA: "BFS with a queue; each outer loop drains one level (snapshot queue size) into a row.",
    prompt: "Return the level-order traversal of a binary tree (a list of levels).",
    examples: "[3,9,20,null,null,15,7] → [[3],[9,20],[15,7]]",
    hints: ["BFS naturally visits by level.", "Record the queue size before draining a level."],
    approach: "queue=[root]; while queue: for _ in range(len(queue)): pop, add val to row, push children; append row.",
    complexity: "Time O(n), Space O(n)",
  },
  {
    id: "kth-smallest-bst", title: "Kth Smallest Element in a BST", diff: "Medium", pattern: "BST In-order",
    drillQ: "kth smallest value in a BST?",
    drillA: "In-order traversal yields sorted order; stop at the kth visited node (iterative stack lets you early-exit).",
    prompt: "Return the kth smallest value (1-indexed) in a BST.",
    examples: "[3,1,4,null,2], k=1 → 1",
    hints: ["In-order of a BST is sorted.", "An explicit stack lets you stop early at k."],
    approach: "Iterative in-order with a stack; decrement k on each pop; when k==0 return node.val.",
    complexity: "Time O(h+k), Space O(h)",
  },

  // ───────────────────────── Tries ─────────────────────────
  {
    id: "implement-trie", title: "Implement Trie (Prefix Tree)", diff: "Medium", pattern: "Trie",
    drillQ: "Design a trie: insert / search / startsWith?",
    drillA: "Node = {children map, isEnd flag}. Walk/create chars; search checks isEnd; startsWith just checks the path exists.",
    prompt: "Implement a trie with insert(word), search(word) (exact), and startsWith(prefix).",
    examples: "insert('apple'); search('app')→false; startsWith('app')→true; insert('app'); search('app')→true",
    hints: ["Each node maps a char to a child node.", "A boolean marks a complete word."],
    approach: "Root node; insert walks/creates children then sets isEnd; search walks then returns isEnd; startsWith walks then returns true.",
    complexity: "Time O(L) per op, Space O(total chars)",
  },

  // ───────────────────────── Heap / Priority Queue ─────────────────────────
  {
    id: "kth-largest-stream", title: "Kth Largest Element in a Stream", diff: "Easy", pattern: "Min-Heap",
    drillQ: "Maintain the kth largest value as numbers stream in?",
    drillA: "Min-heap of size k; push each value, pop when size>k; the heap root is the kth largest.",
    prompt: "Design a class that, given k and a stream, returns the kth largest element after each add().",
    examples: "k=3, add 3,5,10,9,4 → 4,5,5,8,8 (per stream)",
    hints: ["You only care about the top k.", "A size-k min-heap's root IS the kth largest."],
    approach: "Heapify initial; on add push then if len>k pop; return heap[0].",
    complexity: "Time O(log k) per add, Space O(k)",
  },
  {
    id: "median-data-stream", title: "Find Median from Data Stream", diff: "Hard", pattern: "Two Heaps",
    drillQ: "Running median of a stream?",
    drillA: "Max-heap (lower half) + min-heap (upper half), kept balanced; median = top(s). Rebalance after each add.",
    prompt: "Design a structure supporting addNum(x) and findMedian() over a growing stream.",
    examples: "add 1,2 → 1.5 ; add 3 → 2",
    hints: ["Split data into a lower half and an upper half.", "Keep sizes within 1; medians sit at the heap tops."],
    approach: "Push to maxHeap (lower); move its top to minHeap; if minHeap bigger move back. Median = avg/top by parity.",
    complexity: "Time O(log n) add, O(1) median; Space O(n)",
  },

  // ───────────────────────── Backtracking ─────────────────────────
  {
    id: "subsets", title: "Subsets", diff: "Medium", pattern: "Backtracking",
    drillQ: "Generate all subsets (power set)?",
    drillA: "DFS over index i: include nums[i] then recurse, exclude then recurse. Record at every node. 2^n total.",
    prompt: "Return all possible subsets of a set of distinct integers (the power set).",
    examples: "[1,2,3] → [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]",
    hints: ["At each element: take it or skip it.", "Record the current path at each step."],
    approach: "backtrack(i,path): record path; for j in [i..n): add nums[j], recurse j+1, pop.",
    complexity: "Time O(n·2ⁿ), Space O(n) recursion",
  },
  {
    id: "combination-sum", title: "Combination Sum", diff: "Medium", pattern: "Backtracking",
    drillQ: "All combos that sum to target (reuse allowed)?",
    drillA: "DFS with a start index to avoid permutations; subtract candidate from remaining; recurse with SAME index (reuse).",
    prompt: "Given distinct candidates and a target, return all unique combinations summing to target. Each number may be reused unlimited times.",
    examples: "candidates=[2,3,6,7], target=7 → [[2,2,3],[7]]",
    hints: ["Use a start index so you don't double-count orderings.", "Reuse = recurse with the same index."],
    approach: "dfs(i,remain,path): if remain==0 record; for j in [i..n): if c[j]<=remain add, dfs(j,remain−c[j]), pop.",
    complexity: "Time O(2^t) worst, Space O(t)",
  },
  {
    id: "permutations", title: "Permutations", diff: "Medium", pattern: "Backtracking",
    drillQ: "All permutations of distinct numbers?",
    drillA: "DFS tracking used[]; at each level pick any unused number, recurse, undo. n! leaves.",
    prompt: "Return all permutations of an array of distinct integers.",
    examples: "[1,2,3] → 6 permutations",
    hints: ["Track which elements are already placed.", "Swap-in-place is an alternative to a used set."],
    approach: "backtrack(path,used): if full record; for each unused i: mark, add, recurse, unmark/pop.",
    complexity: "Time O(n·n!), Space O(n)",
  },
  {
    id: "word-search", title: "Word Search", diff: "Medium", pattern: "Backtracking / Grid DFS",
    drillQ: "Does a word exist along a path in a grid (no cell reuse)?",
    drillA: "DFS from each cell matching word[k]; mark visited (e.g. overwrite), recurse 4 dirs for k+1, restore on backtrack.",
    prompt: "Given a board of letters, return true if a word can be formed from sequentially adjacent (4-dir) cells without reusing a cell.",
    examples: "board ABCCED..., word='ABCCED' → true",
    hints: ["Try starting from every cell.", "Mark a cell used during the path, restore after."],
    approach: "dfs(r,c,k): if k==len true; bounds/mismatch false; temp=board[r][c]; mark '#'; try 4 dirs k+1; restore.",
    complexity: "Time O(m·n·4^L), Space O(L)",
  },

  // ───────────────────────── Graphs ─────────────────────────
  {
    id: "num-islands", title: "Number of Islands", diff: "Medium", pattern: "Grid BFS/DFS",
    drillQ: "Count connected groups of '1's in a grid?",
    drillA: "Scan cells; on an unvisited '1', flood-fill (BFS/DFS) the whole island marking visited; count++ each new flood.",
    prompt: "Given a grid of '1' (land) and '0' (water), return the number of islands (4-directional connectivity).",
    examples: "grid with two land clusters → 2",
    hints: ["Each unvisited land cell starts a new island.", "Flood the whole island so you don't recount."],
    approach: "For each cell: if '1' and unvisited, count++ and DFS/BFS marking all connected land visited.",
    complexity: "Time O(m·n), Space O(m·n) worst",
  },
  {
    id: "clone-graph", title: "Clone Graph", diff: "Medium", pattern: "Graph DFS + Hash Map",
    drillQ: "Deep-copy a connected undirected graph?",
    drillA: "Map original→clone; DFS/BFS: create clone on first visit, then wire clone.neighbors from mapped originals.",
    prompt: "Return a deep copy of a connected undirected graph (each node has a val and a list of neighbors).",
    examples: "1-2, 1-4, 2-3, 3-4 → identical structure, new nodes",
    hints: ["Avoid infinite loops on cycles — remember what you've cloned.", "A map from old node to new node is the key."],
    approach: "dfs(node): if in map return clone; create clone, map it; for nb in neighbors append dfs(nb) to clone.neighbors.",
    complexity: "Time O(V+E), Space O(V)",
  },
  {
    id: "course-schedule", title: "Course Schedule", diff: "Medium", pattern: "Topological Sort / Cycle Detect",
    drillQ: "Can all courses be finished given prerequisites?",
    drillA: "It's cycle detection on a directed graph. Kahn's (indegree BFS) — finishable iff all nodes processed. Or DFS 3-color.",
    prompt: "Given numCourses and prerequisite pairs [a,b] (b before a), return true if you can finish all courses.",
    examples: "2, [[1,0]] → true ; 2, [[1,0],[0,1]] → false",
    hints: ["A prerequisite chain is a directed edge.", "A cycle makes it impossible."],
    approach: "Kahn: compute indegrees; queue zero-indegree; pop, decrement neighbors, enqueue new zeros; count==numCourses?",
    complexity: "Time O(V+E), Space O(V+E)",
  },
  {
    id: "pacific-atlantic", title: "Pacific Atlantic Water Flow", diff: "Medium", pattern: "Multi-source Grid DFS",
    drillQ: "Cells whose water can reach BOTH oceans?",
    drillA: "DFS inward from each ocean's border (uphill: only to ≥ neighbors); answer = cells reachable from both sets.",
    prompt: "Given a height grid, return cells from which water can flow to both the Pacific (top/left) and Atlantic (bottom/right) edges. Water flows to equal-or-lower neighbors.",
    examples: "5×5 island grid → list of [r,c]",
    hints: ["Reverse the problem: start from the oceans and climb.", "Intersect the two reachable sets."],
    approach: "BFS/DFS from each border into cells with height ≥ current; build reachP and reachA sets; return their intersection.",
    complexity: "Time O(m·n), Space O(m·n)",
  },

  // ───────────────────────── Dynamic Programming (1D) ─────────────────────────
  {
    id: "climbing-stairs", title: "Climbing Stairs", diff: "Easy", pattern: "DP (1D)",
    drillQ: "Ways to climb n stairs taking 1 or 2 steps?",
    drillA: "Fibonacci: ways(n)=ways(n−1)+ways(n−2). Two rolling variables.",
    prompt: "You can climb 1 or 2 steps at a time. How many distinct ways to reach the top of n stairs?",
    examples: "n=3 → 3 (1+1+1, 1+2, 2+1)",
    hints: ["The last move was a 1-step or a 2-step.", "That's the Fibonacci recurrence."],
    approach: "a,b=1,1; repeat n times b=a+b style; return.",
    complexity: "Time O(n), Space O(1)",
  },
  {
    id: "house-robber", title: "House Robber", diff: "Medium", pattern: "DP (1D)",
    drillQ: "Max sum of non-adjacent houses?",
    drillA: "dp[i]=max(skip=dp[i−1], rob=dp[i−2]+nums[i]); roll two vars.",
    prompt: "Maximize money robbed from houses in a line without robbing two adjacent houses.",
    examples: "[2,7,9,3,1] → 12",
    hints: ["For each house: rob it (+ best up to i−2) or skip it (best up to i−1).", "Only two previous states matter."],
    approach: "prev2,prev1=0,0; for x: cur=max(prev1, prev2+x); prev2=prev1; prev1=cur; return prev1.",
    complexity: "Time O(n), Space O(1)",
  },
  {
    id: "coin-change", title: "Coin Change", diff: "Medium", pattern: "DP (Unbounded Knapsack)",
    drillQ: "Fewest coins to make an amount (∞ supply)?",
    drillA: "dp[a]=min over coins of dp[a−coin]+1; dp[0]=0; unreachable=∞.",
    prompt: "Given coin denominations and an amount, return the fewest coins to make it, or −1 if impossible.",
    examples: "coins=[1,2,5], amount=11 → 3 (5+5+1)",
    hints: ["Build up amounts 0..target.", "Best for amount a uses best of a−coin."],
    approach: "dp=[0]+[∞]*amount; for a in 1..amount: dp[a]=min(dp[a−c]+1) over coins c≤a; return dp[amount] or −1.",
    complexity: "Time O(amount·coins), Space O(amount)",
  },
  {
    id: "lis", title: "Longest Increasing Subsequence", diff: "Medium", pattern: "DP / Patience",
    drillQ: "Length of the longest strictly increasing subsequence?",
    drillA: "O(n²): dp[i]=1+max(dp[j]) for j<i,nums[j]<nums[i]. O(n log n): patience — binary-search a 'tails' array.",
    prompt: "Return the length of the longest strictly increasing subsequence.",
    examples: "[10,9,2,5,3,7,101,18] → 4 ([2,3,7,101])",
    hints: ["O(n²) DP is the natural first solution.", "For O(n log n), keep the smallest tail for each length."],
    approach: "tails=[]; for x: replace first tail ≥ x (bisect_left) or append; answer=len(tails).",
    complexity: "Time O(n log n), Space O(n)",
  },
  {
    id: "word-break", title: "Word Break", diff: "Medium", pattern: "DP (1D)",
    drillQ: "Can a string be segmented into dictionary words?",
    drillA: "dp[i]=true if some j<i has dp[j] and s[j:i] in dict; dp[0]=true; answer dp[n].",
    prompt: "Given a string s and a dictionary, return true if s can be segmented into a space-separated sequence of dictionary words.",
    examples: "s='leetcode', dict=['leet','code'] → true",
    hints: ["dp[i] = can the prefix of length i be segmented?", "Try every split point j with a dictionary word ending at i."],
    approach: "dp[0]=true; for i in 1..n: dp[i]=any(dp[j] and s[j:i] in words for j<i).",
    complexity: "Time O(n²·L), Space O(n)",
  },

  // ───────────────────────── Dynamic Programming (2D) ─────────────────────────
  {
    id: "unique-paths", title: "Unique Paths", diff: "Medium", pattern: "DP (2D)",
    drillQ: "Paths from top-left to bottom-right moving only right/down?",
    drillA: "dp[i][j]=dp[i−1][j]+dp[i][j−1]; first row/col=1. (Or C(m+n−2, m−1).)",
    prompt: "Count distinct paths in an m×n grid from top-left to bottom-right moving only down or right.",
    examples: "m=3, n=7 → 28",
    hints: ["Each cell's paths = paths from above + paths from left.", "Edges have exactly one way."],
    approach: "1D rolling row of n ones; for each row: row[j]+=row[j−1]; answer row[n−1].",
    complexity: "Time O(m·n), Space O(n)",
  },
  {
    id: "lcs", title: "Longest Common Subsequence", diff: "Medium", pattern: "DP (2D)",
    drillQ: "Length of the longest common subsequence of two strings?",
    drillA: "dp[i][j]: if chars match dp[i−1][j−1]+1 else max(dp[i−1][j],dp[i][j−1]).",
    prompt: "Return the length of the longest common subsequence of two strings.",
    examples: "'abcde','ace' → 3 ('ace')",
    hints: ["Compare the last characters of each prefix.", "Match → diagonal+1; mismatch → drop one char (max)."],
    approach: "Grid (m+1)×(n+1); fill by recurrence; answer dp[m][n]. Can roll to O(n) space.",
    complexity: "Time O(m·n), Space O(m·n)",
  },

  // ───────────────────────── Greedy ─────────────────────────
  {
    id: "max-subarray", title: "Maximum Subarray", diff: "Medium", pattern: "Kadane / Greedy",
    drillQ: "Largest sum of a contiguous subarray?",
    drillA: "Kadane: cur=max(x, cur+x); best=max(best,cur). Reset when running sum goes negative.",
    prompt: "Find the contiguous subarray with the largest sum and return that sum.",
    examples: "[-2,1,-3,4,-1,2,1,-5,4] → 6 ([4,-1,2,1])",
    hints: ["A negative running sum is dead weight — drop it.", "Track best-ending-here and best-overall."],
    approach: "cur=best=nums[0]; for x in rest: cur=max(x,cur+x); best=max(best,cur).",
    complexity: "Time O(n), Space O(1)",
  },
  {
    id: "jump-game", title: "Jump Game", diff: "Medium", pattern: "Greedy",
    drillQ: "Can you reach the last index given max jump lengths?",
    drillA: "Track farthest reachable; if i ever exceeds it → false; reach=max(reach,i+nums[i]); reachable if reach≥last.",
    prompt: "Each element is your max jump length from that index. Return true if you can reach the last index.",
    examples: "[2,3,1,1,4] → true ; [3,2,1,0,4] → false",
    hints: ["Track the farthest index you can currently reach.", "If your position passes that frontier, you're stuck."],
    approach: "reach=0; for i,x: if i>reach return false; reach=max(reach,i+x); return true.",
    complexity: "Time O(n), Space O(1)",
  },

  // ───────────────────────── Intervals ─────────────────────────
  {
    id: "merge-intervals", title: "Merge Intervals", diff: "Medium", pattern: "Intervals",
    drillQ: "Merge all overlapping intervals?",
    drillA: "Sort by start; iterate, if cur.start ≤ last.end extend last.end=max(...), else push cur.",
    prompt: "Given intervals, merge all overlapping ones and return the non-overlapping result.",
    examples: "[[1,3],[2,6],[8,10],[15,18]] → [[1,6],[8,10],[15,18]]",
    hints: ["Sorting by start makes overlaps adjacent.", "Extend the last merged interval's end."],
    approach: "Sort by start; for each iv: if iv[0]<=res[-1][1] res[-1][1]=max(end,iv[1]) else res.append(iv).",
    complexity: "Time O(n log n), Space O(n)",
  },
  {
    id: "insert-interval", title: "Insert Interval", diff: "Medium", pattern: "Intervals",
    drillQ: "Insert a new interval into a sorted non-overlapping list and merge?",
    drillA: "Add all intervals ending before new.start; merge all overlapping with new; add the rest.",
    prompt: "Given sorted non-overlapping intervals and a new interval, insert it and merge as needed.",
    examples: "[[1,3],[6,9]], new=[2,5] → [[1,5],[6,9]]",
    hints: ["Three phases: before, overlapping (merge), after.", "Expand new.start/end while overlapping."],
    approach: "Push all iv.end<new.start; while overlap, new=[min start,max end]; push new; push the rest.",
    complexity: "Time O(n), Space O(n)",
  },
  {
    id: "non-overlapping-intervals", title: "Non-overlapping Intervals", diff: "Medium", pattern: "Greedy Intervals",
    drillQ: "Min intervals to remove so none overlap?",
    drillA: "Sort by END; greedily keep intervals whose start ≥ last kept end; removals = total − kept.",
    prompt: "Return the minimum number of intervals to remove so the rest are non-overlapping.",
    examples: "[[1,2],[2,3],[3,4],[1,3]] → 1",
    hints: ["Keeping the interval that ends earliest leaves the most room.", "Sort by end, not start."],
    approach: "Sort by end; prevEnd=−∞; for iv: if iv.start>=prevEnd keep, prevEnd=iv.end; else removals++.",
    complexity: "Time O(n log n), Space O(1)",
  },

  // ───────────────────────── Bit / Math ─────────────────────────
  {
    id: "single-number", title: "Single Number", diff: "Easy", pattern: "Bit Manipulation (XOR)",
    drillQ: "Every element appears twice except one — find it, O(1) space?",
    drillA: "XOR all elements; pairs cancel (x^x=0), leaving the unique number.",
    prompt: "Every element appears twice except one. Find that single one in O(n) time, O(1) space.",
    examples: "[4,1,2,1,2] → 4",
    hints: ["x ^ x = 0 and x ^ 0 = x.", "Order doesn't matter for XOR."],
    approach: "Fold XOR over the array; result is the lone element.",
    complexity: "Time O(n), Space O(1)",
  },
  {
    id: "number-of-1-bits", title: "Number of 1 Bits", diff: "Easy", pattern: "Bit Manipulation",
    drillQ: "Count set bits (popcount) of an integer?",
    drillA: "Loop: n &= n−1 clears the lowest set bit; count iterations until n==0.",
    prompt: "Return the number of '1' bits in the binary representation of an unsigned integer.",
    examples: "11 (1011) → 3",
    hints: ["Checking each bit is O(32).", "n & (n−1) drops the lowest set bit — loop runs once per set bit."],
    approach: "count=0; while n: n&=n−1; count++. Return count.",
    complexity: "Time O(#set bits), Space O(1)",
  },
  {
    id: "missing-number", title: "Missing Number", diff: "Easy", pattern: "Math / XOR",
    drillQ: "One number missing from 0..n — find it?",
    drillA: "Expected sum n(n+1)/2 minus actual sum. (Or XOR indices with values.)",
    prompt: "Given an array of n distinct numbers from the range [0,n], return the missing one.",
    examples: "[3,0,1] → 2",
    hints: ["The full set 0..n has a known sum.", "XOR of indices and values also isolates it."],
    approach: "missing = n*(n+1)/2 − sum(nums). Or XOR i and nums[i] for all, plus n.",
    complexity: "Time O(n), Space O(1)",
  },
];
